"""Added Permission table for access control

Revision ID: 85fa78589538
Revises: b5766e0ed9fb
Create Date: 2025-09-26 14:05:11.630918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fa78589538'
down_revision = 'b5766e0ed9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role', 'endpoint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    # ### end Alembic commands ###
